const byId=id=>document.getElementById(id);const status=text=>byId('accountStatus').textContent=text;
(async()=>{try{const r=await fetch('/api/auth/me',{cache:'no-store'});if(!r.ok)throw Error('Unable to load your account.');const {user}=await r.json();if(!user){status('Sign in to manage your account.');return;}byId('signedIn').hidden=false;byId('accountName').textContent=user.username;byId('accountId').textContent=user.id;status('Your account is connected.');}catch(e){status(e.message);}})();
byId('keyForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;try{const r=await fetch('/api/auth/recovery-key',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:byId('currentPassword').value})});const d=await r.json();if(!r.ok)throw Error(d.error);byId('recoveryKey').value=d.recoveryKey;byId('keyResult').hidden=false;byId('currentPassword').value='';status('Recovery key created. Store it privately before closing this window.');}catch(e){status(e.message);}finally{button.disabled=false;}};
byId('signOut').onclick=async()=>{try{const r=await fetch('/api/auth/logout',{method:'POST'});if(!r.ok)throw Error('Unable to sign out.');for(const key of ['8bitgpu-player-name','8bitgpu-account-active','8bitgpu-avatar-outfit'])localStorage.removeItem(key);if(parent!==window)parent.location.reload();else location.href='login.html';}catch(e){status(e.message);}};

async function accessRequest(body){const r=await fetch('/api/chat/access',{method:body?'POST':'GET',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
async function loadMembers(){const data=await accessRequest();byId('ownerAccess').hidden=false;byId('memberList').replaceChildren();for(const member of data.members){const row=document.createElement('div'),name=document.createElement('span'),button=document.createElement('button');name.textContent=member.username+(member.allowed?' · Member':' · Access removed');button.type='button';button.textContent=member.allowed?'Remove access':'Restore access';button.onclick=async()=>{button.disabled=true;try{await accessRequest({username:member.username,allowed:!member.allowed});await loadMembers();status('Room access updated.');}catch(e){status(e.message);button.disabled=false;}};row.append(name,button);byId('memberList').append(row);}}
byId('inviteForm').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{const result=await accessRequest({username:byId('memberName').value.trim(),allowed:true});byId('memberName').value='';await loadMembers();status(result.username+' can now join the arcade with their own account.');}catch(e){status(e.message);}finally{e.submitter.disabled=false;}};
loadMembers().catch(()=>{});
