const el=id=>document.getElementById(id);
const MAP_BOUNDS={minX:6,maxX:94,minY:12,maxY:94};
let x=48,y=73,target=null,keys=new Set(),joined=false,myId=null,messages=[],lastLog='',timer=null,inflight=false,delay=1500,muted=false,movingFrame=0,lastFrame=0;
const beings=new Map();
const clampPosition=(x,y)=>({x:Math.max(MAP_BOUNDS.minX,Math.min(MAP_BOUNDS.maxX,x)),y:Math.max(MAP_BOUNDS.minY,Math.min(MAP_BOUNDS.maxY,y))});
function status(text){el('roomStatus').textContent=text;}
async function api(path,body,method){const r=await fetch('/api/chat/'+path,{method:method||(body===undefined?'GET':'POST'),headers:body===undefined?{}:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const d=await r.json();if(!r.ok){const e=Error(d.error||'Room connection unavailable.');e.code=d.code;e.status=r.status;throw e;}return d;}
function positionSelf(){const node=beings.get(myId);if(node){node.style.left=x+'%';node.style.top=y+'%';node.style.zIndex=String(Math.round(y));}}
function renderMembers(members){const active=new Set(members.map(m=>m.id));for(const[id,node]of beings){if(!active.has(id)){node.remove();beings.delete(id);}}
 for(const m of members){let node=beings.get(m.id);if(!node){node=document.createElement('div');node.className='being'+(m.id===myId?' self':'');node.dataset.userId=m.id;const bubble=document.createElement('span');bubble.className='bubble';const effect=document.createElement('span');effect.className='emote-effect';effect.setAttribute('aria-hidden','true');const name=document.createElement('button');name.type='button';name.className='name being-profile-link';name.textContent=m.username+(m.id===myId?' (you)':'');name.title=m.id===myId?'Your MyPixel page':'Open '+m.username+'\'s MyPixel page';node.append(bubble,effect,name);el('players').append(node);beings.set(m.id,node);}const signature=JSON.stringify(m.avatar);if(node.dataset.avatar!==signature){node.querySelectorAll('img').forEach(i=>i.remove());for(const key of ['extra','body','ears','head','eyes','hair','fit']){const source=m.avatar.layers[key];if(!source)continue;const img=document.createElement('img');img.src=source;img.alt='';img.onerror=()=>img.remove();const adjustment=m.avatar.adjustments[key];if(adjustment)img.style.transform=`translate(${adjustment.x}%,${adjustment.y}%) scale(${adjustment.scale})`;node.insertBefore(img,node.querySelector('.bubble'));}node.dataset.avatar=signature;}for(const emote of ['dance','smoke','laugh','spin','wave'])node.classList.toggle('emote-'+emote,m.emote===emote&&m.emoteUntil>Date.now());node.style.left=(m.id===myId?x:m.x)+'%';node.style.top=(m.id===myId?y:m.y)+'%';node.style.zIndex=String(Math.round(m.id===myId?y:m.y));}
 el('roomCount').textContent=members.length+' in the room';renderBubbles();
}
function renderBubbles(){for(const[id,node]of beings){const latest=[...messages].reverse().find(m=>m.userId===id&&Date.now()-m.createdAt<8000);node.querySelector('.bubble').textContent=latest?latest.body.slice(0,160)+(latest.body.length>160?'…':''):'';}}
function renderLog(data){messages=data.messages;if(!myId){const seed=[...data.user.id].reduce((n,c)=>n+c.charCodeAt(0),0);x=36+seed%19;y=66+seed%9;}myId=data.user.id;muted=data.mutedUntil>Date.now();el('identity').textContent=data.user.username+(data.owner?' · Owner':' · Member');el('roomMessage').disabled=false;el('sendMessage').disabled=muted;const signature=JSON.stringify(messages);if(signature!==lastLog){const log=el('roomMessages'),bottom=log.scrollHeight-log.scrollTop-log.clientHeight<50;const rows=messages.map(m=>{const p=document.createElement('p'),name=document.createElement('strong'),text=document.createElement('span');name.textContent=m.username;text.textContent=m.body;p.append(name,text);return p;});log.replaceChildren(...rows);if(bottom||!lastLog)log.scrollTop=log.scrollHeight;lastLog=signature;}renderBubbles();}
async function sync(){if(inflight||document.hidden)return;inflight=true;clearTimeout(timer);try{const data=await api('messages');renderLog(data);const room=await api('presence',{x,y});joined=true;el('roomGate').hidden=true;renderMembers(room.members);delay=1500;status(muted?'You are temporarily muted. You can still walk around.':'');}catch(e){joined=false;keys.clear();target=null;el('roomMessage').disabled=true;el('sendMessage').disabled=true;el('roomCount').textContent='Not connected';status(e.message);delay=Math.min(delay*2,15000);if(e.code==='join_required'){el('roomGate').hidden=false;delay=0;}else if(e.status===401||e.status===403){el('players').replaceChildren();beings.clear();el('roomMessages').replaceChildren();messages=[];lastLog='';delay=0;}}finally{inflight=false;if(delay&&!document.hidden)timer=setTimeout(sync,delay);}}
el('joinRoom').onclick=async()=>{try{await api('join',{adult:el('adult').checked,rules:el('rules').checked});delay=1500;await sync();}catch(e){status(e.message);}};
el('roomComposer').onsubmit=async e=>{e.preventDefault();el('sendMessage').disabled=true;try{await api('messages',{message:el('roomMessage').value});el('roomMessage').value='';await sync();}catch(error){status(error.message);}finally{el('sendMessage').disabled=!joined||muted;}};
document.querySelectorAll('[data-emote]').forEach(button=>button.addEventListener('click',async()=>{if(!joined)return status('Enter the room before using an emote.');button.disabled=true;try{await api('emote',{emote:button.dataset.emote});await sync();}catch(error){status(error.message);}finally{button.disabled=false;}}));
el('roomCamera').onclick=async()=>{if(!joined)return status('Enter the room before taking a picture.');const button=el('roomCamera');button.disabled=true;try{const stream=await navigator.mediaDevices.getDisplayMedia({video:{displaySurface:'browser'},audio:false});const video=document.createElement('video');video.srcObject=stream;await video.play();const scale=Math.min(1,1400/Math.max(video.videoWidth,video.videoHeight)),canvas=document.createElement('canvas');canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);canvas.getContext('2d').drawImage(video,0,0,canvas.width,canvas.height);stream.getTracks().forEach(track=>track.stop());let blob=null;for(const quality of [.82,.62,.42,.25]){blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',quality));if(blob?.size<=512*1024)break;}if(!blob||blob.size>512*1024)throw Error('That picture is too detailed. Try a smaller capture.');const response=await fetch('/api/profile/images/desktop1',{method:'PUT',headers:{'content-type':'image/webp'},body:blob});const data=await response.json();if(!response.ok)throw Error(data.error||'Picture could not save.');status('Room photo saved in Desktop Backgrounds.');}catch(error){status(error.name==='NotAllowedError'?'Camera cancelled.':error.message);}finally{button.disabled=false;}};
function animate(time){const dt=Math.min(.05,(time-lastFrame)/1000||.016);lastFrame=time;let dx=0,dy=0;for(const k of keys){if(k==='a'||k==='arrowleft')dx--;if(k==='d'||k==='arrowright')dx++;if(k==='w'||k==='arrowup')dy--;if(k==='s'||k==='arrowdown')dy++;}if(dx||dy)target=null;else if(target){dx=target.x-x;dy=target.y-y;if(Math.hypot(dx,dy)<.5){target=null;dx=dy=0;el('walkMarker').hidden=true;}}const length=Math.hypot(dx,dy);if(length){const step=Math.min(length,23*dt);const next=clampPosition(x+dx/length*step,y+dy/length*step);x=next.x;y=next.y;positionSelf();}if(joined&&(keys.size||target))movingFrame=requestAnimationFrame(animate);else movingFrame=0;}
function startMoving(){if(!movingFrame){lastFrame=performance.now();movingFrame=requestAnimationFrame(animate);}}
el('mapStage').addEventListener('pointerdown',e=>{if(!joined||e.button!==0||e.target.closest('.being-profile-link'))return;const r=e.currentTarget.getBoundingClientRect();target=clampPosition((e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100);el('walkMarker').style.left=target.x+'%';el('walkMarker').style.top=target.y+'%';el('walkMarker').hidden=false;e.currentTarget.focus();startMoving();});
document.addEventListener('keydown',e=>{if(!joined||e.target.closest('textarea,input,button,a'))return;const key=e.key.toLowerCase();if(['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright'].includes(key)){e.preventDefault();keys.add(key);startMoving();}});document.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();target=null;});
function leave(){keys.clear();target=null;clearTimeout(timer);if(joined)fetch('/api/chat/presence',{method:'DELETE',keepalive:true}).catch(()=>{});}
document.addEventListener('visibilitychange',()=>{if(document.hidden)leave();else{delay=1500;sync();}});window.addEventListener('pagehide',leave);sync();


