const $=id=>document.getElementById(id);
let me=null,owner=false,timer=null,delay=3000,reportId=null,lastMessages='',busy=false,lastConnectionError='';
async function api(path,body){const response=await fetch('/api/chat/'+path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const data=await response.json();if(!response.ok){const error=new Error(data.error||'Unable to connect.');error.code=data.code;error.status=response.status;throw error;}return data;}
function notice(text){$('status').textContent=text;}
function button(label,action){const b=document.createElement('button');b.type='button';b.textContent=label;b.addEventListener('click',()=>Promise.resolve(action()).catch(e=>notice(e.message)));return b;}
function render(data){me=data.user;owner=data.owner;$('identity').textContent='Signed in as '+me.username;$('logout').hidden=false;$('room').hidden=false;$('join').hidden=true;$('moderation').hidden=!owner;
 const signature=JSON.stringify(data.messages);
 if(signature!==lastMessages){const log=$('messages'),bottom=log.scrollHeight-log.scrollTop-log.clientHeight<50;const fragment=document.createDocumentFragment();for(const message of data.messages){const row=document.createElement('article');row.className='message';const name=document.createElement('strong');name.textContent=message.username;const time=document.createElement('time');time.dateTime=new Date(message.createdAt).toISOString();time.textContent=new Date(message.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});const text=document.createElement('p');text.textContent=message.body;if(message.portrait){const face=document.createElement('span');face.className='portrait';face.setAttribute('aria-hidden','true');for(const source of Object.values(message.portrait)){const img=document.createElement('img');img.src=source;img.alt='';img.onerror=()=>img.remove();face.append(img);}row.append(face);}row.append(name,time,text);const actions=document.createElement('div');actions.className='actions';if(message.userId!==me.id){actions.append(button('Report',()=>{reportId=message.id;$('reason').value='';$('reportDialog').showModal();}),button('Block',async()=>{await api('block',{userId:message.userId,blocked:true});await refresh();}));}if(owner){actions.append(button('Delete',()=>moderate({action:'delete',messageId:message.id})));if(message.userId!==me.id)actions.append(button('Mute 1h',()=>moderate({action:'mute',userId:message.userId})),button('Ban',()=>moderate({action:'ban',userId:message.userId})));}row.append(actions);fragment.append(row);}if(!data.messages.length){const empty=document.createElement('p');empty.textContent='The Garden is quiet. Start the conversation!';fragment.append(empty);}log.replaceChildren(fragment);if(bottom||!lastMessages)log.scrollTop=log.scrollHeight;lastMessages=signature;}
 $('blocks').replaceChildren(...data.blocks.map(b=>button('Unblock '+b.username,async()=>{await api('block',{userId:b.id,blocked:false});await refresh();})));$('send').disabled=data.mutedUntil>Date.now();if(data.mutedUntil>Date.now())notice('You are muted until '+new Date(data.mutedUntil).toLocaleTimeString());else if(status.textContent.startsWith('You are muted until '))notice('');
}
async function refresh(){if(busy)return;busy=true;clearTimeout(timer);try{const data=await api('messages');render(data);$('connection').textContent='Connected';delay=3000;}catch(e){$('connection').textContent='Not connected';lastConnectionError=e.message;notice(e.message);delay=Math.min(delay*2,30000);if(e.code==='join_required'){$('join').hidden=false;$('room').hidden=true;}if(e.status===401||e.status===403){$('room').hidden=true;$('moderation').hidden=true;delay=0;}}finally{busy=false;if(delay&&!document.hidden)timer=setTimeout(refresh,delay);}}
async function moderate(body){await api('moderation',body);notice('Moderation change saved.');await refresh();await reports();}
async function reports(){const data=await api('moderation');$('reports').replaceChildren();for(const r of data.reports){const row=document.createElement('div');const text=document.createElement('p');text.textContent=r.username+': '+r.body+' — Report: '+r.reason;row.append(text,button('Delete message',()=>moderate({action:'delete',messageId:r.messageId})),button('Resolve',()=>moderate({action:'resolve',messageId:r.messageId})));$('reports').append(row);}if(!data.reports.length)$('reports').textContent='No open reports.';$('restrictions').replaceChildren();for(const m of data.members){const row=document.createElement('div');row.textContent=m.username+' ';if(m.banned)row.append(button('Unban',()=>moderate({action:'unban',userId:m.id})));if(m.mutedUntil>Date.now())row.append(button('Unmute',()=>moderate({action:'unmute',userId:m.id})));$('restrictions').append(row);}}
$('joinButton').onclick=async()=>{try{await api('join',{adult:$('adult').checked,rules:$('rules').checked});notice('Welcome to the Garden.');delay=3000;await refresh();}catch(e){notice(e.message);}};
$('composer').onsubmit=async event=>{event.preventDefault();$('send').disabled=true;try{await api('messages',{message:$('message').value});$('message').value='';notice('');await refresh();}catch(e){notice(e.message);}finally{$('send').disabled=false;}};
$('reportForm').onsubmit=async event=>{event.preventDefault();try{await api('report',{messageId:reportId,reason:$('reason').value});$('reportDialog').close();notice('Report sent to the room owner.');}catch(e){notice(e.message);}};
$('cancelReport').onclick=()=>$('reportDialog').close();$('refreshReports').onclick=()=>reports().catch(e=>notice(e.message));
$('logout').onclick=async()=>{try{const r=await fetch('/api/auth/logout',{method:'POST'});if(!r.ok)throw Error('Unable to sign out. Try again.');localStorage.removeItem('8bitgpu-player-name');localStorage.removeItem('8bitgpu-account-active');localStorage.removeItem('8bitgpu-avatar-outfit');clearTimeout(timer);location.href='login.html';}catch(e){notice(e.message);}};
document.addEventListener('visibilitychange',()=>{clearTimeout(timer);if(!document.hidden){delay=3000;refresh();}});window.addEventListener('pagehide',()=>clearTimeout(timer));refresh();


