let friends=[], events=[], activeFriend=null, currentTab='friends';
const el=id=>document.getElementById(id);
async function api(path,method='GET',body){const r=await fetch(path,{method,cache:'no-store',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Unable to connect.');return d;}
const status=message=>el('status').textContent=message;
function button(label,action){const b=document.createElement('button');b.type='button';b.textContent=label;b.onclick=async()=>{b.disabled=true;try{await action();}catch(e){status(e.message);}finally{b.disabled=false;}};return b;}
function row(name){const r=document.createElement('div');r.className='social-row';const n=document.createElement('strong');n.textContent=name;r.append(n);return r;}
function openProfile(username){if(parent!==window)parent.postMessage({type:'8bitgpu-open-profile',username},location.origin);else location.href='profile.html?u='+encodeURIComponent(username);}
function openRoom(app){if(parent!==window)parent.postMessage({type:'8bitgpu-open-app',app},location.origin);else location.href=app==='arcade'?'arcade.html':'chat.html';}
async function loadFriends(){const d=await api('/api/friends');friends=d.friends;el('list').replaceChildren();el('requests').replaceChildren();
 for(const f of friends){const r=row(f.username);r.append(button('MyPixel',()=>openProfile(f.username)),button('DM / Invite',async()=>{activeFriend=f;el('conversation').hidden=false;el('conversationTitle').textContent=f.username;await loadMessages();el('message').focus();}),button('Remove',async()=>{await api('/api/friends/'+f.id,'DELETE');if(activeFriend?.id===f.id){activeFriend=null;el('conversation').hidden=true;}await loadFriends();}));el('list').append(r);}
 if(!friends.length)el('list').textContent='No accepted friends yet. Send a request to get started.';
 for(const f of d.requests){const r=row(f.username+(f.incoming?' wants to be friends':' · Request sent'));if(f.incoming)r.append(button('Accept',async()=>{await api('/api/friends/'+f.id,'PUT',{});await loadFriends();status('Friend request accepted.');}));r.append(button(f.incoming?'Decline':'Cancel',async()=>{await api('/api/friends/'+f.id,'DELETE');await loadFriends();}));el('requests').append(r);}
 if(!d.requests.length)el('requests').textContent='No pending requests.';
}
async function loadEvents(){const d=await api('/api/social/events');events=d.events;el('count').textContent=d.unread||'';el('events').replaceChildren();
 for(const e of events){const r=row(e.username+(e.seen?'':' · New'));const p=document.createElement('p');p.textContent=e.kind==='request'?'Sent you a friend request.':e.kind==='accepted'?'Accepted your friend request.':e.kind==='invite'?'Invited you to '+(e.body==='arcade'?'Arcade Lounge':'Chat.exe'):e.body;r.append(p);if(e.kind==='invite')r.append(button('Open room',()=>openRoom(e.body)));if(e.kind==='request')r.append(button('Manage request',()=>showTab('friends')));if(e.kind==='message')r.append(button('Reply',async()=>{const f=friends.find(f=>f.id===e.sender);if(!f)throw Error('Accept a friendship before messaging.');activeFriend=f;el('conversation').hidden=false;el('conversationTitle').textContent=f.username;await loadMessages();el('message').focus();}));el('events').append(r);}
 if(!events.length)el('events').textContent='No notifications yet.';
}
async function loadMessages(){if(!activeFriend)return;const d=await api('/api/social/messages?friend='+encodeURIComponent(activeFriend.id));el('messages').replaceChildren();for(const m of d.messages){const p=document.createElement('p');p.textContent=m.username+': '+m.body;el('messages').append(p);}el('messages').scrollTop=el('messages').scrollHeight;}
async function loadTop(){const d=await api('/api/social/top');el('slots').replaceChildren();for(let i=0;i<8;i++){const l=document.createElement('label');l.textContent=(i+1)+'. ';const s=document.createElement('select');s.setAttribute('aria-label','Top friend '+(i+1));s.add(new Option('Empty',''));for(const f of friends)s.add(new Option(f.username,f.id));s.value=d.friends[i]?.id||'';l.append(s);el('slots').append(l);}}
async function showTab(tab){currentTab=tab;for(const id of ['friends','inbox','top'])el(id).hidden=id!==tab;if(tab==='top')await loadTop();if(tab==='friends')await loadFriends();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>showTab(b.dataset.tab).catch(e=>status(e.message)));
el('add').onsubmit=async e=>{e.preventDefault();try{await api('/api/friends','POST',{username:el('name').value.trim()});el('name').value='';await loadFriends();status('Friend request sent.');}catch(e){status(e.message);}};
el('saveTop').onclick=async()=>{try{await api('/api/social/top','PUT',{ids:[...el('slots').querySelectorAll('select')].map(s=>s.value).filter(Boolean)});status('Your Top 8 is saved.');}catch(e){status(e.message);}};
el('read').onclick=async()=>{try{await api('/api/social/read','POST',{through:events[0]?.id||0});await loadEvents();}catch(e){status(e.message);}};
el('send').onsubmit=async e=>{e.preventDefault();if(!activeFriend)return;try{await api('/api/social/send','POST',{friend:activeFriend.id,kind:'message',body:el('message').value});el('message').value='';await loadMessages();status('Message sent.');}catch(e){status(e.message);}};
el('invite').onclick=async()=>{if(!activeFriend)return;try{await api('/api/social/send','POST',{friend:activeFriend.id,kind:'invite',body:el('room').value});status('Room invitation sent. Existing room access rules apply.');}catch(e){status(e.message);}};
let polling=false;async function refresh(){if(document.hidden||polling)return;polling=true;try{await loadFriends();await loadEvents();await loadMessages();}catch(e){status(e.message);if(/Sign in/.test(e.message)){friends=[];activeFriend=null;el('list').replaceChildren();el('events').replaceChildren();el('conversation').hidden=true;}}finally{polling=false;}}
refresh();setInterval(refresh,6000);document.addEventListener('visibilitychange',refresh);
