const savedCart=JSON.parse(localStorage.getItem("8bitgpu-store-cart")||"[]");
const S={products:[],cart:new Map(savedCart),category:"All",config:null},$=id=>document.getElementById(id),money=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"});
async function api(url,options){const r=await fetch(url,options),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Store connection failed.");return d}
function tabs(){const cats=["All",...new Set(S.products.map(p=>p.category))];$("categoryTabs").innerHTML=cats.map(c=>`<button class="${c===S.category?"active":""}" data-category="${c}">${c}</button>`).join("")}
function products(){const list=S.category==="All"?S.products:S.products.filter(p=>p.category===S.category);$("productGrid").innerHTML=list.length?list.map(p=>`<article class="product-card"><span class="tag">${p.type}</span><h2>${p.name}</h2><p>${p.description}</p><footer><strong class="price">${p.price==null?"QUOTE":money.format(p.price)}</strong>${p.price==null?`<a href="${p.inquiryUrl}" target="_blank" rel="noopener">INQUIRE ↗</a>`:`<button data-add="${p.id}">ADD TO BAG</button>`}</footer></article>`).join(""):`<article class="stocking-card"><strong>STOCKING THE SHELVES…</strong><p>The marketplace bones are online. Products are coming next.</p></article>`}
function payload(){return[...S.cart].map(([id,quantity])=>({id,quantity}))}
function cart(){let total=0,count=0,html="";for(const[id,q]of [...S.cart]){const p=S.products.find(x=>x.id===id);if(!p||p.price==null){S.cart.delete(id);continue}total+=p.price*q;count+=q;html+=`<div class="cart-line"><strong>${p.name}</strong><span>${money.format(p.price*q)}</span><span class="qty"><button data-qty="${id}" data-delta="-1">−</button>${q}<button data-qty="${id}" data-delta="1">+</button></span><button data-remove="${id}">remove</button></div>`}localStorage.setItem("8bitgpu-store-cart",JSON.stringify([...S.cart]));$("cartItems").innerHTML=html;$("emptyCart").hidden=!!count;$("cartCount").textContent=`${count} ITEM${count===1?"":"S"}`;$("cartTotal").textContent=money.format(total);pay(count)}
function pay(count){const box=$("paypalButtonContainer");box.innerHTML="";$("demoCheckout").hidden=S.config?.paypalReady||!count;if(!count||!S.config?.paypalReady||!window.paypal)return;paypal.Buttons({style:{layout:"vertical",shape:"pill",color:"blue"},createOrder:async()=>(await api("/api/store/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({items:payload()})})).id,onApprove:async d=>{const r=await api(`/api/store/orders/${encodeURIComponent(d.orderID)}/capture`,{method:"POST"});S.cart.clear();cart();$("orderSuccess").hidden=false;$("orderSuccess").innerHTML=`<strong>Payment complete ✦</strong><p>Order ${r.orderId} is confirmed.</p>`},onError:e=>notice(e.message)}).render(box)}
function notice(m){$("storeNotice").hidden=false;$("storeNotice").textContent=m}
function sdk(){if(!S.config.paypalReady)return Promise.resolve();return new Promise((ok,no)=>{const s=document.createElement("script");s.src=`https://www.paypal.com/sdk/js?client-id=${encodeURIComponent(S.config.clientId)}&currency=USD&components=buttons`;s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
document.addEventListener("click",e=>{const a=e.target.closest("[data-add]");if(a){S.cart.set(a.dataset.add,(S.cart.get(a.dataset.add)||0)+1);cart()}const t=e.target.closest("[data-category]");if(t){S.category=t.dataset.category;tabs();products()}const q=e.target.closest("[data-qty]");if(q){const n=(S.cart.get(q.dataset.qty)||0)+Number(q.dataset.delta);n>0?S.cart.set(q.dataset.qty,n):S.cart.delete(q.dataset.qty);cart()}const r=e.target.closest("[data-remove]");if(r){S.cart.delete(r.dataset.remove);cart()}});
(async()=>{try{const d=await api("/api/store/catalog");S.products=d.products;S.config=d.checkout;$("checkoutMode").textContent=d.checkout.paypalReady?"PAYPAL CHECKOUT ONLINE":"CHECKOUT SETUP MODE";tabs();products();await sdk();cart();if(!d.checkout.paypalReady)notice("Shop UI is ready. Add PayPal sandbox credentials and confirm prices to enable checkout.")}catch(e){notice(e.message)}})();
